package com.example.highermathapp_sic.model

enum class TaskType {
    ADDITION,
    SUBTRACTION,
    MULTIPLICATION_BY_NUM,
    MULTIPLICATION_BY_MATRIX_1,
    MULTIPLICATION_BY_MATRIX_2,
    DET_2X2,
    DET_3X3,
    MINOR,
    INVERSE,
    CRAMER_RULE,
    SEQUENCE_LIMIT,
    FUNCTIONAL_LIMIT_1,
    FUNCTIONAL_LIMIT_2,
    FUNCTION_ANALYSIS_1,
    FUNCTION_ANALYSIS_2,
    INDEFINITE_INTEGRALS,
    DEFINITE_INTEGRALS_1,
    DEFINITE_INTEGRALS_2
}